test gcc -Wall -pedantic -Werror -Wextra -std=gnu89 positive_or_negative.c 0-main.c -o 0-main gcc -Wall -pedantic -Werror -Wextra -std=gnu89 positive_or_negative.c 0-main.c -o 0-maingcc -Wall -pedantic -Werror -Wextra -std=gnu89 positive_or_negative.c 0-main.c -o 0-main gcc -Wall -pedantic -Werror -Wextra -std=gnu89 positive_or_negative.c 0-main.c -o 0-mainΩ≈çÇ◊
clear
root@29a3045e7dd0:/alx-low_level_programming/0x02-functions_nested_loops# vi 100-times_table.c

root@29a3045e7dd0:/alx-low_level_programming/0x02-functions_nested_loops# vi 100-main.c
root@29a3045e7dd0:/alx-low_level_programming/0x02-functions_nested_loops# gcc -Wall -pedantic -Werror -Wextra -std=gnu89 _putchar.c 100-main.c 100-times_table.c -o 100-times_table
100-main.c: In function ‘main’:
100-main.c:10:5: error: implicit declaration of function ‘print_times_table’; did you mean ‘times_table’? [-Werror=implicit-function-declaration]
   10 |     print_times_table(3);
      |     ^~~~~~~~~~~~~~~~~
      |     times_table
cc1: all warnings being treated as errors
root@29a3045e7dd0:/alx-low_level_programming/0x02-functions_nested_loops# vin main.h> zΩvoid print_times_table(int n);void print_times_table(int n);
bash: syntax error near unexpected token vagrant box updatevagrant provision--provision('
root@29a3045e7dd0:/alx-low_level_programming/0x02-functions_nested_loops# vim main.h
root@29a3045e7dd0:/alx-low_level_programming/0x02-functions_nested_loops# gcc -Wall -pedantic -Werror -Wextra -std=gnu89 _putchar.c 100-main.c 100-times_table.c -o 100-times_table
root@29a3045e7dd0:/alx-low_level_programming/0x02-functions_nested_loops# ./100-times_table
0,   0,   0,   0
0,   1,   2,   3
0,   2,   4,   6
0,   3,   6,   9

0,   0,   0,   0,   0,   0
0,   1,   2,   3,   4,   5
0,   2,   4,   6,   8,  10
0,   3,   6,   9,  12,  15
0,   4,   8,  12,  16,  20
0,   5,  10,  15,  20,  25

0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0
0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12
0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24
0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36
0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48
0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60
0,   6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72
0,   7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84
0,   8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96
0,   9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108
0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120
0,  11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132
0,  12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144
root@29a3045e7dd0:/alx-low_level_programming/0x02-functions_nested_loops# git add .
root@29a3045e7dd0:/alx-low_level_programming/0x02-functions_nested_loops# git commit -m 100-times_table
[master 02ebb91] 100-times_table
 4 files changed, 66 insertions(+)
 create mode 100644 0x02-functions_nested_loops/100-main.c
 create mode 100755 0x02-functions_nested_loops/100-times_table
 create mode 100644 0x02-functions_nested_loops/100-times_table.c
root@29a3045e7dd0:/alx-low_level_programming/0x02-functions_nested_loops# git push
Username for 'https://github.com': michaeladavis2308
Password for 'https://michaeladavis2308@github.com':
Enumerating objects: 10, done.
Counting objects: 100% (10/10), done.
Delta compression using up to 2 threads
Compressing objects: 100% (7/7), done.
Writing objects: 100% (7/7), 3.78 KiB | 3.78 MiB/s, done.
Total 7 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/michaeladavis2308/alx-low_level_programming.git
   dc78254..02ebb91  master -> master
root@29a3045e7dd0:/alx-low_level_programming/0x02-functions_nested_loops#
  [Restored Feb 23, 2023 at 8:30:08 AM]
Last login: Thu Feb 23 08:19:17 on ttys001
Restored session: Thu Feb 23 08:19:17 GMT 2023
[3] 2867
macbookair@MacBooks-MacBook-Air ~ % vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/focal64' version '20230202.0.0' is up to date...
==> default: A newer version of the box 'ubuntu/focal64' for provider 'virtualbox' is
==> default: available! You currently have version '20230202.0.0'. The latest is version
==> default: '20230215.0.0'. Run  to update.
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 6.1.38
    default: VirtualBox Version: 7.0
==> default: Mounting shared folders...
    default: /vagrant => /Users/macbookair
==> default: Machine already provisioned. Run  or use the
==> default: flag to force provisioning. Provisioners marked to run always will still run.
macbookair@MacBooks-MacBook-Air ~ % vagrant provision
macbookair@MacBooks-MacBook-Air ~ % vagrant ssh
Welcome to Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-137-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Thu Feb 23 08:35:55 UTC 2023

  System load:  1.29              Processes:               122
  Usage of /:   4.6% of 38.70GB   Users logged in:         0
  Memory usage: 20%               IPv4 address for enp0s3: 10.0.2.15
  Swap usage:   0%

 * Strictly confined Kubernetes makes edge and IoT secure. Learn how MicroK8s
   just raised the bar for easy, resilient and secure K8s cluster deployment.

   https://ubuntu.com/engage/secure-kubernetes-at-the-edge

 * Introducing Expanded Security Maintenance for Applications.
   Receive updates to over 25,000 software packages with your
   Ubuntu Pro subscription. Free for personal use.

     https://ubuntu.com/pro

Expanded Security Maintenance for Applications is not enabled.

0 updates can be applied immediately.

Enable ESM Apps to receive additional future security updates.
See https://ubuntu.com/esm or run: sudo pro status

The list of available updates is more than a week old.
To check for new updates run: sudo apt update
New release '22.04.1 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Last login: Wed Feb 22 11:22:32 2023 from 10.0.2.2
vagrant@ubuntu-focal:~$ ssh 29a3045e7dd0@29a3045e7dd0.b44aa7f8.alx-cod.online
29a3045e7dd0@29a3045e7dd0.b44aa7f8.alx-cod.online's password:
root@29a3045e7dd0:/# ls
alx-low_level_programming  alx-system_engineering-devops  Betty  boot  etc   lib    lib64   media  opt   root  sbin  sys  usr
alx-pre_course             alx-zero_day                   bin    dev   home  lib32  libx32  mnt    proc  run   srv   tmp  var
root@29a3045e7dd0:/# cd alx-low_level_programming/
root@29a3045e7dd0:/alx-low_level_programming# ls
0x00-hello_world  0x01-variables_if_else_while  0x02-functions_nested_loops  README.md
root@29a3045e7dd0:/alx-low_level_programming# mkdir 0x03-debugging
root@29a3045e7dd0:/alx-low_level_programming# cd 0x03-debugging/
root@29a3045e7dd0:/alx-low_level_programming/0x03-debugging# vi README.md
root@29a3045e7dd0:/alx-low_level_programming/0x03-debugging# ls
README.md
root@29a3045e7dd0:/alx-low_level_programming/0x03-debugging# touch 0-main.c main.h
root@29a3045e7dd0:/alx-low_level_programming/0x03-debugging# ls
0-main.c  main.h  README.md
root@29a3045e7dd0:/alx-low_level_programming/0x03-debugging# vi 0-main.c
root@29a3045e7dd0:/alx-low_level_programming/0x03-debugging# vi main.h
root@29a3045e7dd0:/alx-low_level_programming/0x03-debugging# gcc -Wall -pedantic -Werror -Wextra -std=gnu89 positive_or_negative.c 0-main.c -o 0-main
gcc: error: positive_or_negative.c: No such file or directory
root@29a3045e7dd0:/alx-low_level_programming/0x03-debugging# git add .
root@29a3045e7dd0:/alx-low_level_programming/0x03-debugging# git commit -m test